<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>DPA.Practica01._21200159.CORE</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Core\Entities\" />
    <Folder Include="Core\Interfaces\" />
    <Folder Include="Core\Services\" />
    <Folder Include="Infrastructure\Data\" />
    <Folder Include="Infrastructure\Repositories\" />
  </ItemGroup>

</Project>
